### ISSUE TITLE
When opening "Toan" or "Dasset", should show articles

### ISSUE THREAD

**Issue by myamaricia** [Teknologforeningen/tf-joomla-template#24]
When opening "Toan" or "Dasset" the articles should be shown fully, not only the headlines as a list. More like "Nyheter"

**Comment by oehnstro** [comment]
Joomla content issue, fixed by selecting blog layout and including all subcategories.

<img width="431" alt="screenshot 2015-12-15 22 25 43" src="https://cloud.githubusercontent.com/assets/917061/11823110/da1ef9d0-a37a-11e5-8bdc-7b21308d57f6.png">
