### ISSUE TITLE
Take headline away from "Tjänster"

### ISSUE THREAD

**Issue by myamaricia** [Teknologforeningen/tf-joomla-template#26]
The text Tjänster should not be visible on the page "Tjänster", only a list of items.

**Comment by oehnstro** [comment]
Joomla issue, fixed by editing "Options" in menu item.

<img width="475" alt="screenshot 2015-12-15 22 19 35" src="https://cloud.githubusercontent.com/assets/917061/11822937/f3acb762-a379-11e5-9520-7b47a3fd6c88.png">
