### ISSUE TITLE
"Pil" links are not bolded

### ISSUE THREAD

**Issue by myamaricia** [Teknologforeningen/tf-joomla-template#27]
I.e. here https://medlem.teknologforeningen.fi/index.php/material the "läs mer" link should be bolded.
Also some headlines are not bolded even though they should be, for example "protokoll" under "material"  and "DRINK-TASTING MED FILMTEMA!" under "nyheter"

**Comment by oehnstro** [comment]
@myamaricia  Are all items that have the arrow supposed to be bolded? Does this only work for h3 elements with an a-element inside them?

**Comment by oehnstro** [comment]
Fixed by d0f11576e4fdacf45328890ef5b1294bb7bb15c6 and 479cbb620c54ddb1b9a4d8d5e05348bd88983708
