### ISSUE TITLE
Gallery photo preview incorrectly says you need to log in

### ISSUE THREAD

**Issue by Andeye** [Teknologforeningen/tf-joomla-template#40]
"Message

Please login first"
Is shown when previewing an image.

Reproduction steps:
1. Log in
2. Go to gallery
3. Click on an image to view a larger version
4. The mentioned text is shown
Expected results: You are already logged in and only the image and no message should be shown

**Comment by tlangens** [comment]
Fix'd, let me know if issue reappears
